server:
  port: 8080

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    default-property-inclusion: non_null
    time-zone: America/Lima

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 28800000
  scan:
    pin-attempts: 3
    session-timeout-minutes: 5

logging:
  level:
    com.machy: DEBUG
    org.springframework.security: INFO
